sudo: false
language: java
jdk:
- openjdk8
- oraclejdk8
- openjdk11
addons:
  sonarcloud:
    organization: tallencewassimakachi-github
    token:
      secure: KajWo/xEfiaAUTdAON8xYU2Z413cgzTC/Mz++h6TSGywGcbZKaGjQ7Zl7j71fbN8SV2PhTkDKp2LRl+lCDe67ALYGzF7X9efIccp7YRVeGSLcScdMXdlBF1uiNIN2RDlhvZl4TTQQ1ZALV55mmZbtZ17UOJlc8jKth3ITazsEAOfk1oRcmlUbObws52e/aTQ/KjFtTzmowrGEZOewHkLA+c4A9m9hWpHYuW9en6b3YJypSgeZPJ5VGYUiClBiEVldF9vAqCieWferZPYUKrXoqlDOxISZJadnV5UxGBB5G5WCbqvtDsx75EgEVHZXCXP34esdck/AopUyfHdHOkO9M44LUMLyubfrjy4XtrNKhe+GBiNTplrg16UucEZ3N1YTLfH7k4iKyWL15E07WEJh0JLcmm3H7goUmE/oAv7S5G95oFwHVpsItERGkYhVEJ2FXV1db184RdPBl4U9AvpUk7PRqrXLV6I8tk4cXvuWaXw+pSvM259OmHI4zXNGuXxhRUK2wiFUnoE1fDgvrzvQ+Ylzn4eUVVms7UtKalZ9ysh/AhRtPpHX+fMmUFUts9RyllqJr/SXwe3/r9xO2/ldQgtOGkO/kq5q1Li3Do8BEBT7xIoAZwCl6o4O7RMAjujnhCrCEs1dFt5Lt76AFCXxjfITGq6IlbWNUrZmiP4mbU=
  apt:
    packages:
    - oracle-java8-installer
git:
  quiet: true
  depth: 50
  submodules: true
branches:
  only:
  - "/^.*$/"
  except:
  - gh-pages
notifications:
  email:
  - w.akachi@tallence.com
install: "/bin/true"
script:
  - chmod +x ./util/scripts/*.sh
  - "./util/scripts/ci-build.sh"

jobs:
  include:
    - stage: deploy - snapshot
      if: branch = develop AND type != pull_request
      jdk: openjdk8
      script:
        - chmod +x ./util/scripts/*.sh
        - ./util/scripts/ci-deploy.sh travis snapshot
#    - stage: deploy - release
#      if: branch = master AND type != pull_request AND tag =~ ^v-[0-9]+\.[0-9]+\.[0-9]+$
#      jdk: openjdk8
#      script:
#        - chmod +x ./util/scripts/*.sh
#        - ./util/scripts/ci-deploy.sh travis release


env:
  global:
  #- secure: xWDSD9TZyX6FWnIifXuBOH9bgAKoXSQcr06BnOkYXo+SNoZIvrfBxh927ux/06lejxCGNwE7i+M2x5ysRslNzIq73JlGo05iQNPlDhB5M8GPlwTOqW4Ug4R5pQA7doImThVeUI+JrlOSGsDdZbkRSenaYoRhV6IRIvoPA+AhXix2b5VKjF9QHFecjTp/FRpA2nJ0RafnKhWb89HvyOPmputa3MiuPBnffWp76BZlZuyJ8//P1zWniqs6qOiFfCEpVEXvvN/gU9v6iyvJzB2RKTUyva8mfTUdJ7DAI/VTS2cC446CK4eB5rGkW1S+RShf3iVK7NnU31hNClZ12sEozP0IhLxDYefEe3kRCeirPIeG4reMXNVhuzlo2/ym33Sof64Z3mcQfboZcdrZQUuRRb/fCemH/vW1v5dzo6XDDSlIzRaeKhYOG4bK6so0N3B0XqrTUrElTM3/q1KnmMfDhhfOTDAUN14jUOUg3kMZZQvPeEW4yxyTqWDX8s1LI6dzVWY+U0GbphJ3TVJqyU0T7QSvbMAoLCFEpBcifDFgi84cohK62bkVVtV+SsgOeAbEy62g1JQfq5sXO9Ca9VtUsCIL2O3ZKSL751uLAnlLj6GxHSIGDUYi70fI3WH1K9Z1GrRbmk0odqRC6bsJUzH3bTAa9NJbY9fyekocYI76YPQ=
  - secure: 0GXqI9zlVjhFU3BZprjJ9uH0uLrAwZ1DJVtldcikapprr1By1sj4gFJJEgI7oogCEhZ28G45MyIit3iXK6B8yLvvd99GNhALQdJqAUaPJTwHVuMNe7qIqxPa1V5KAMvxWM25SZV39WUgz7epQHV9xcLCPTM3u7mHjRqHzxKoRL0JINrrIFYvfzm0FDgFO3OVbFqxqhOEK2orxPCcUS6l+04pfgq61FQAKOgKLTbVOMI8tKyY8s9Y3+y/Vz08ZxS/FjfAYYWgwEQ+kTuW0VxCHA9yJrMNmxl6kwkF2mxqPZ84yhi3E1UYNaLVucQXWvI4dgBJgfj4912JrSuwnqX8+qZvt+bSmaRlHNR9c/wBbaC9wBrKlTf94ngOjvuWYvM3ereFRScvaoEHQEaoaLXy206hlieJ39+Api9eLJgFB0xFYAkP3eQdlYTBAlsr8IfxzlOWqIMzV5KOPMljlImqvADlXkjZrMlCYkfkgE4wb4YXDKTomw4KkXp0hZZGBJNbVWS+mtriDaA4nIvBvtvHfAv+tuNM0DGA+PSUwQ5HhFaJ5KBa3+oqh3DFFPt5VHL2DHx/UuxI20KLlChzQivIEquFBPqCZ4hyEVdcgsJAZaIw4IP2Lht5Ynmviii2CXO1NXygTkJDMj+ohOUUjsyD8ibBKN3Un08pN5kogNWYkXM=
  - secure: RSnE/qdiEOQqCV7lrNooZ5WUM/JTNVETdOHzeCIl+2eGIHqNCqcJOKA9nmeW+FUt4d90BWdoXs6wDOr8HQYJsjvAwMmc9ozfwxHr8vmekJcHz4S/Q3Jb8EjJFp/Uv3tWTI0DSCzNE8ebD5riH7Ze2+bzRyzRK+XGqfbW6nHMZKWhxWDDbYt18UVnQ79fzkNchSx13Phv8yg0mEhYT5Qnemi0Yga/d87jKCIK3/eyu8VpwcOnoXXQYd4BwlEvip9JBa8TQOjjs665Nx0moT6VxYR+U0L2aOj8+pmbAsjm8otmAgwEqzuAN6T3xmbdBgg+fspmi+xGTWgV/op4kqP3fDia26PpndGK6S9e6sTgCIGgq+7xrdJbE4/+VI5QbwLTbF/pG0MZteHnm5GD/owAMCPE2Fv2csqIgWfaNMTeToMHDrde7XOpFugAZC9QKUH99blMgMnB0aLU9wvBOZRKHH+oeveey0oYPczIi+RdqOSuPcE+uQG9adkx3l7zHMmeGcas/DjBI4VEU0MVxN31RewtMmkJH+x5sA8KFXXUD1HQKjwbvOZeEMy9xn8q+F/IGS8LKetu/pshtRkKOogdto9Ch711LYuuczA4Adn8cABFLytmAUsbWI59vLcxpIXlu1I7K11npXV5XCgP4NxnDPoVoEZX1jMtiU6vc/Wj79k=
  - secure: K8QjmTcGfP5loTtSn5Miu2co7OeQyP29r3Q9zfPFVX+eH5R6ukxTwAwL9ZwE62jXYwKxtoFUrK+/PYSJaQPQLHYPV3tLYwRrsk42okdmpyNEAyx02c91lHb9w6glT34tXO59jpdhLCIv6KqiDWJNv0AhxSeVPB8pVW5K3t8m6be7eAL4fYFn8ziaOF5P3kHlf4yQoTStP4Y22KbT7AA9qPx/m84GunZ0kCkYyR6RQpVIZWt/QvxMa4p4ECJYvxOfraCdt+i/oX+6BeWACqOwb1StvYwzfjr+cLwA0DosXIu3cVSd+ZqMY1DX74BDIkHfHw+jsULIaqwK7pA2vlNKZSf/FOdvZXsytYYVkL4a8QSHJETFr+nJd8UuujC1n03dUdr+aFRspxUzpCQ/eLJ919KI7Ef7Z7R8N5YTN143ulw4u+MAhwdKIv613kbZmIj21Sr5SzFiEEBJtlpzfArgC+yrZgjvZzoh7UZb49XLSO97W29hH3DyyYxUj1Hlm8n2Jfjh1SV4DZgEec+ZZLyCWAvYqeeWmvSd7vfn+lMUmO+y0wUS+KajOAiDuU1YKzBdfRJt+nJRC5BOjhiKvAI8ufZqkARCJ+PkyyAvDTmLpzCZv/PIAWf+gJ7Axf6QKzM6D3OaUfXyby4qODIXrYKlkBf17y9rhYRn8DgDaQRYk7g=
  - secure: EYCl2wa7qO0gV1/PhIz5SeTwUWPiuBic2acMCT5eqH5SXRxctvRMCCLJlBAC28U9bv+UpxcwfSyZlZMT9EiilC6/Z3F/hhVUbFbnfXW96x9LNolvolyC5JXNmzPvmBuESGnwTGQg1rp8XiAPXBgbt1UZp6ADP/ld50IFWoLbs1A8TROT8ayGw48zUmLsc9GHCvX6orIJsSs9BkKEpLMFOvmpcbmCuwVoN/0QVzfFw2Ow0vdinqO8S/4qp5dQuCTdsuW5IC+KnbxT9GGu34hcqKa2FOklMyCO0f7f1D5UjZzjta6iEZBByDFkYf05TXVOjfO0DB4gAop7EiYM+dnFnEHLV5AN0NX3AwjkPcyB9gj620rdXXv4hzrdDFXyj9NmZjfUy94UvquPk0viFoI/KNULh46JBFQqkdKlg78M1gKjvVBH3wGheT9qcd8YsgEdZbQkTEoDrhnUsqvcb1bhFcBu4iGO/jbvLqSHhu3OzNFGRgicdqNk378SIurCnJpSoqfEJS2xLhFppJGgjr5/EjvyqlcvFOoufwNJnKJ89QQ9U3S1ujOGNx/08QdYuEEnzHtvX4+l3pVNVabhVf27QfqMISNocnRHDBEDpMfkC0wMIzxFNVgOLM1fDsdKaaBNWt11SFVQIEdoQKFzo9Aw4lPnvTGfwmuyCv8MqHCcEpY=
  - secure: IhVQ1j/vDFjB0LRTfnkQjudsj/vEH5tM6wwUGrk9ya1CLhzQ9a6TwoM0zSyRnG1Qo8TtucG6xN6370WEk38/sT9Vf/IOaKwfBtJrj25146YaRoxsz84ZwJ8V4W7JWMD0ctn6urc/ZRBfpsy2k85mb2pkZDTs5/LaR8uSVN+9sk2q40IhoYJtxdqNgZYY+6N76qZZQK9w4WH+02kq+Rcdd9AGf3LO5eO8q/32Nby3SGwbkY3rVmXP//GuMOLQthJTzHjchiDA7sdQVQIHpqzNBpDLfDxWR4qd59yiNZKAhoEXxQXwzMptla9r/WADEOcnEAvT5jqYmm0Gqnp7tjzAjSnzwhIurYp110CKwA4AjwiQKUYA71zR9zMQd2UrEGjckYd0i+Cnh+t48P7pAYxRO6AYCXjP0u5JqmsJfknRpNGXkNXLTWAFECFcx6sw4Im98MrdjIohz+YYU7yL1d5/ORx+42oaodutwwoNYMumZKOyP0Eh7dw4cBzy+0AmIbrznPJ0hCy+jcPevHzjcnBLgSxbWuC5WfiInw6MY5CABTRBwf+xr/J0IA71cT6YEmRp9M4NkSC65P3o0yfSKLWW+nmN7JxW5QzsmDSw8M0GxDhSpB3rcQQmPU71t+od4slYfj9H+uNof+nh2adS+wdjxmRj5AddU9LyLKQlIddjeBs=
deploy:
  provider: releases
  api_key:
    secure: 1Rn0n5n7Te5FoRWl3gSXalngaKJgAzrDwNskqBm3zzk5Wa8Xs6y0PUngWu7hZGwc/6GO+GCnQy8Z5NOgOQF4DVJw9lODe7itDq26/SDNnvVEhw5Tpm2qcBFFvX9IqhB1xl5ksNdG3Rp/RrrDRp2wJtqFeP05++embeujnQBHbrhf4DDBxBTGWBP4Iy/g2nJI7cQDOCQBY71bfU82ZmjYKO7o5V/Qv3/uSjtPvGEM+XYGJ5uKpv/DJEAzbuuR2H8/YpWif3pKnV41pQgvykBEclNAgyG80kfkFJ99JIRvvzkJPDk2BZ0LF1YOsJkcZAwYVmcGR6GlYVCehI4xctf0G4QidEr0gqVh80/SGY1fPejfA6/NR/iU/Mx25cTKt9zdzs28GkauOEy3/333eS8bguHpYmGhIzahJxTcCowAhygXTnUL88oI6nN2A39HipsRiI3lrQ3m2emXWekcL6/0HRDDi+bVIG38P1TPsvTx3ILNVybxScMOT3QA+erLrFdpBWwPUQt4Mx497Gus9yyGEbkO7EF9sYUnkvkCjORUFd+jZjWYdYKhTNvuuMWuXULiEeXcmeNu4h9tUqpqbQ7g0vgGL/c7TsDrL8zADpFMuCBAg5mw7lXHa5OlpBBKPZUbXNb+w2g9nH2PJtrv1futKDxSDQxNOuNgTf95inL3Uwg=
  file: target/maj-*.jar
  on:
    repo: TallenceWassimAkachi/maj
    branch: master
    tags: true
